### PR TITLE
Create mariem-hiring.dmg

### PR DESCRIPTION
**Pull request by mariemf**
This is the first draft of my work, what do you think?

### CODE REVIEW

**Comment by em3059** [comment]
Maybe you should elaborate on the second question. I also think we covered other issues during this class like how to attract developers. What do you think ?
: Image of tech fair

**Comment by mariemf** [comment]
Good idea, Etienne! I just found this valuable resource to help me elaborate more: https://www.youtube.com/watch?v=yctfSyBQQDU&list=WL&index=4
You might use it for your project as well.

**Comment by em3059** [comment]
Wow ! This is the Professor Bell's video ! It's great ! 
Thanks for the link :smiley: @mariemf

**Comment by em3059** [comment]
i think your file is good to go ! :+1:

**Comment by mariemf** [comment]
Okay! Thanks @em3059

**Pull request merged**
