### PR TITLE
Create website-vs-app-pros-and-cons

### PR DESCRIPTION
**Pull request by em3059**
Sorry for the mistake. What do u think of that ? Should I write a little bit more on the subject ?

### CODE REVIEW

**Comment by em3059** [comment]
@mariemf 
I changed the file accordingly
I talked about stuff like [PhoneGap](https://en.wikipedia.org/wiki/PhoneGap) or native apps ?
What do you think ?

**Comment by mariemf** [comment]
What a good idea!
83815_6m7kzbvhruz5xx82jjlutw166zjm8y_sourirechat_h173710_l

**Comment by em3059** [comment]
let's be more professional :pray: @mariemf can I merge ?

**Comment by mariemf** [comment]
Yes sir :+1:

**Pull request merged**
